import SessionProviders from "@/utils/SessionProvider"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
// import AppContext from "@/context/AppContext";
import stripe from "@/utils/stripe"


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const stripePromise = loadStripe(process.env.STRIPE_PUBLIC_KEY! as string)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders>
        {children}
        </SessionProviders>
      </body>
    </html>
  )
}
